import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Button from "react-bootstrap/Button";

import { Container } from "react-bootstrap";
import fetchData from "src/fetching/fetch";
import { useEffect, useState } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const [data, setData] = useState(null);

  useEffect(() => {
    const getData = async () => {
      console.log("running");
      const receivedData = await fetchData(
        "http://localhost:1337/api/rate",
        "GET",
      );
      console.log(receivedData);
      setData(receivedData.attributes.apr);
    };
    getData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={styles.main}>
        <div className={styles.center}>
        <Image
        className={styles.logo}
        src="/next.svg"
        alt="Next.js Logo"
        width={180}
        height={37}
        priority
        />
        <div className={styles.thirteen}>
        <Image
        src="/thirteen.svg"
        alt="13"
        width={40}
              height={31}
              priority
              />
              </div>
              </div>
            </main> */}
      <h3>Bank of England rate change announcement</h3>
      <p>
        Following the 0.50% rise in the Bank of England Base Rate we have
        reviewed our current mortgage rates. We will be making the following
        changes with effect from 1st February 2023:
      </p>
      <ul>
        <li>
          BM Standard Variable Rate currently at{" "}
          <span style={{ color: "red" }}>{data}%</span> will increase by 0.5% to
          7.84%. If your mortgage is affected by the rate change, we'll write to
          you to let you know your new monthly payment before it is due.
        </li>
      </ul>
      <p>
        Use our Rate Change Calculator to get an idea of how much a monthly
        mortgage payment might change by, following a Bank of England Base Rate
        change.
      </p>
      Find out more about the{" "}
      <Link href="/terminals">
        Bank of England base rate and your mortgage.
      </Link>
    </>
  );
}
